apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: chuo-test
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/cuipinghuo/rhtap-test:d3cc5057adb24baaed5359043deaf525c8e1c980@sha256:62c5e074e8a90adaa5ab5cd785f353a8fa3aeefc2e9fa832ac91e3511985b596
        name: container-image  
