apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: python-test
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/cuipinghuo/rhtap-test:dfdc89649a96a74a9c08d0fe1d6dd614ac6ca890
        name: container-image  
